[project]
name = "gridwin"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pillow>=12.1.0",
    "pyinstaller>=6.18.0",
    "pyside6>=6.10.1",
    "pywin32>=311",
]
